apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-exporter
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-exporter
  template:
    metadata:
      labels:
        app: kafka-exporter
    spec:
      containers:
        - name: kafka-exporter
          image: danielqsj/kafka-exporter:latest
          ports:
            - name: metrics
              containerPort: 9308
          args:
            - --kafka.server=kafka-controller-0.kafka-controller-headless.kafka.svc.cluster.local:9092
            - --topic.filter=.*
            - --group.filter=.*
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-exporter
  namespace: kafka
spec:
  type: ClusterIP
  selector:
    app: kafka-exporter
  ports:
    - name: metrics
      port: 9308
      targetPort: 9308
