apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-batch-dataset          # 💡 job 이름 변경
  namespace: default
spec:
  sparkConf:
    "spark.hadoop.fs.s3a.impl": "org.apache.hadoop.fs.s3a.S3AFileSystem"
    "spark.hadoop.fs.s3a.endpoint": "s3.ap-northeast-2.amazonaws.com"

  type: Python
  mode: cluster
  image: dwnusa/spark:v3.5.4-amd64
  imagePullPolicy: IfNotPresent
  mainApplicationFile: local:///opt/spark-data/spark_batch_dataset.py
  sparkVersion: 3.5.4

  restartPolicy:
    type: Never

  arguments:             # ✅ Python script 인자 전달 (PostgreSQL → S3)
    # PostgreSQL 연결정보
    - "--pg-table"
    - "datalake_table"
    - "--machine"
    - "machine-1-1"

    # S3 저장 관련
    - "--s3-bucket"
    - "s3a://kas-on-m3k/smd-dataset"
    - "--format"
    - "csv"

    # 최근 N일만 백업
    - "--days"
    - "1"

  driver:
    cores: 1
    memory: 2g
    serviceAccount: spark-operator-spark
    volumeMounts:
      - name: data
        mountPath: /opt/spark-data

  executor:
    cores: 1
    instances: 2            # executor 수 증가
    memory: 2g
    volumeMounts:
      - name: data
        mountPath: /opt/spark-data

  volumes:
    - name: data
      hostPath:
        path: /opt/spark/jobs
