apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-stream-realtime-down
  namespace: default # airflow # spark-operator
spec:
  type: Python
  mode: cluster
  # image: docker.io/library/spark:4.0.0
  image: dwnusa/spark:v3.5.4.1-amd64
  imagePullPolicy: IfNotPresent
  mainApplicationFile: local:///opt/spark-data/spark_stream_realtime_down.py
  sparkVersion: 3.5.4
  restartPolicy:
    type: Never
  arguments:             # ✅ Python script 인자 전달
    - "--pg-host"
    - "10.246.246.33"
    - "--pg-port"
    - "12345"
    - "--pg-db"
    - "testdb"
    - "--pg-user"
    - "dwnusa"
    - "--pg-table"
    - "{{ params.table }}"
    - "--pg-checkpoint-table"
    - "realtime_checkpoint_table"
    - "--job-name"
    - "anomaly_detection_job"
    - "--kafka-bootstrap"
    - "kafka.kafka.svc.cluster.local:9092"
    - "--eph-topic"
    - "{{ params.eph_topic }}"
    - "--checkpoint-location"
    - "/tmp/checkpoint"
    - "--trigger-interval"
    - "60 seconds"
    - "--lookback-minutes"
    - "5"
    - "--pca-k"
    - "4"
    - "--p-value"
    - "0.05"
    # S3 관련
    - "--s3-bucket"
    - "s3a://kas-on-m3k/smd-dataset"
    - "--format"
    - "csv"
  driver:
    cores: 1
    memory: 512m
    serviceAccount: spark-operator-spark
    # ▼▼▼ Spark UI 활성화 핵심 설정 ▼▼▼
    sparkConf:
      "spark.ui.enabled": "true"
      "spark.ui.port": "4040"
    serviceType: NodePort
    exposedPort: 4040
    # ▲▲▲ Spark UI 활성화 핵심 설정 ▲▲▲
    volumeMounts:
      - name: data
        mountPath: /opt/spark-data
  executor:
    cores: 1
    instances: 2
    memory: 512m
#     securityContext:
#       runAsUser: 0
#       runAsGroup: 0
    volumeMounts:
      - name: data
        mountPath: /opt/spark-data
  volumes:
    - name: data
      hostPath:
        path: /opt/spark/jobs