apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-airflow
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /opt/airflow/dags # localpath for airflow dags
  claimRef:
    namespace: airflow
    name: airflow-dags
